name: 'PR Check'
on: [pull_request] # Triggers on any branch
env:
  CI: 'true'
  NX_BASE: ${{ github.event.pull_request.base.sha }}
  BROWSERSTACK_LATEST_BROWSERS_LAUNCHER: 'Playwright'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          # Number of commits to fetch. 0 indicates all history for all branches and tags.
          # Pulls all commits (needed for Lerna)
          fetch-depth: 0

      - name: Setup resources and environment
        uses: ./.github/actions/setup
        id: setup

      - name: Install Dependencies
        run: npm ci --audit=false --fund=false

      - name: Version
        run: |
          node -v
          npm -v

      - name: Build
        run: npm run build:affected

  lint:
    name: Lint
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup resources and environment
        uses: ./.github/actions/setup

      - name: Lint
        run: npm run lint:affected

  test-chrome:
    name: 'Test / Chrome'
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Test
        uses: ./.github/actions/run-test
        with:
          browsers: 'chrome'

  test-firefox:
    name: 'Test / Firefox'
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Test
        uses: ./.github/actions/run-test
        with:
          browsers: 'firefox'

  test-safari:
    name: 'Test / Safari'
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Test
        uses: ./.github/actions/run-test
        with:
          browsers: 'safari'

  scan-sonarcloud:
    name: 'Scan / SonarCloud'
    needs: test-chrome
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup resources and environment
        uses: ./.github/actions/setup

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@c25d2e7e3def96d0d1781000d3c429da22cd6252 # v2.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
